# Generated by Django 2.1.4 on 2019-01-18 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20190113_1654'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='teacher/%Y%m', verbose_name='头像'),
        ),
    ]
