# Generated by Django 2.1.4 on 2019-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_auto_20190119_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, default='org\x81901\\default.png', null=True, upload_to='org/%Y%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='teacher\x81901\\default.png', null=True, upload_to='teacher/%Y%m', verbose_name='头像'),
        ),
    ]
