# Generated by Django 2.1.4 on 2019-01-24 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_auto_20190119_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseorg',
            name='image',
            field=models.ImageField(blank=True, default='org/201901/default.png', null=True, upload_to='org/%Y%m', verbose_name='logo'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='image',
            field=models.ImageField(blank=True, default='teacher/201901/default.png', null=True, upload_to='teacher/%Y%m', verbose_name='头像'),
        ),
    ]
