# Generated by Django 2.1.4 on 2019-01-25 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_auto_20190119_0850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='click_num',
            new_name='click_nums',
        ),
    ]
