# Generated by Django 2.1.4 on 2018-12-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20181223_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailverifyrecord',
            name='code',
            field=models.CharField(max_length=50, verbose_name='验证码'),
        ),
    ]
